### PR TITLE
Update for Anki >= 2.0.27

### LINKED ISSUE #16: Doesn't work with sync protocol in Anki 2.0.27 and greater
SYNC_URL has been renamed to SYNC_BASE, and the "/sync/" part of the URL is no longer needed, so I think the README should be updated.

### PR DESCRIPTION
**Pull request by jdoe0**
Fixes #16.

In addition to anki.sync.SYNC_BASE, anki.sync.SYNC_MEDIA_BASE also needs to be updated to point to the server.

Note that this breaks compatibility with Anki < 2.0.27.

### CODE REVIEW

**Comment by agrueneberg** [comment]
Thanks for looking into this! I noticed that the patch is quite small.
Does this fix both card sync and media sync?

**Comment by jdoe0** [comment]
Both card sync and media sync seemed to work properly when I tested it.

**Comment by dsnopek** [comment]
There were pretty big changes to the way that Anki does media sync in 2.0.27. I'd be really surprised if this was all that was necessary. But if it is, that's awesome. :-)

**Comment by jdoe0** [comment]
Actually, media sync fails silently but card sync works fine. I didn't test it thoroughly the first time.

**Comment by jdoe0** [comment]
Media sync should work now.

**Comment by jdoe0** [comment]
Fixed 403 error when syncing media.

**Comment by jdoe0** [comment]
Added a new commit to allow syncing with AnkiDroid (tested with https://github.com/ankidroid/Anki-Android/pull/680). Addon code in README.rst is also updated for Anki >= 2.0.27.

**Comment by dper** [comment]
@jdoe0 I'm excited to see this new stuff. Thank you!

**Comment by agrueneberg** [comment]
Thanks, @jdoe0! I'll try to find some time this week to test the changes.

**Comment by mydropwizard** [comment]
Has anyone had a chance to test this? Personally, I haven't had the time either, but I'd be more motivated if someone (besides the author) had a successful test with it. :-)

**Comment by dsnopek** [comment]
Has anyone had a chance to test this? Personally, I haven't had the time either, but I'd be more motivated if someone (besides the author) had a successful test with it. :-)

**Comment by Akendo** [comment]
Hey I did test this patches, I synced with the latest version of the Anki Desktop Client(2.0.33). It's working, but the server and client raising error messages.

It's a fresh setup, first sync attempted:

Here the server error message:

```
akendo@x240 ~/s/anki-sync-server> python2 ./ankiserverctl.py debug example.ini 
Starting server in PID 15218.
serving on http://127.0.0.1:27701
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 35904)
Traceback (most recent call last):
  File "/home/akendo/.virtualenvs/anki-sync-server/lib/python2.7/site-packages/paste/httpserver.py", line 1085, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/home/akendo/.virtualenvs/anki-sync-server/lib/python2.7/site-packages/paste/httpserver.py", line 459, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/akendo/.virtualenvs/anki-sync-server/lib/python2.7/site-packages/paste/httpserver.py", line 454, in handle_one_request
    self.wsgi_execute()
  File "/home/akendo/.virtualenvs/anki-sync-server/lib/python2.7/site-packages/paste/httpserver.py", line 304, in wsgi_execute
    self.wsgi_start_response)
  File "/home/akendo/.virtualenvs/anki-sync-server/lib/python2.7/site-packages/paste/translogger.py", line 69, in __call__
    return self.application(environ, replacement_start_response)
  File "/home/akendo/.virtualenvs/anki-sync-server/lib/python2.7/site-packages/paste/urlmap.py", line 216, in __call__
    return app(environ, start_response)
  File "/home/akendo/.virtualenvs/anki-sync-server/lib/python2.7/site-packages/webob/dec.py", line 130, in __call__
    resp = self.call_func(req, *args, **self.kwargs)
  File "/home/akendo/.virtualenvs/anki-sync-server/lib/python2.7/site-packages/webob/dec.py", line 195, in call_func
    return self.func(req, *args, **kwargs)
  File "/home/akendo/src/anki-sync-server/AnkiServer/apps/sync_app.py", line 414, in __call__
    session = self.session_manager.load(hkey, self.create_session)
  File "/home/akendo/src/anki-sync-server/AnkiServer/apps/sync_app.py", line 603, in load
    cursor.execute("SELECT skey, user, path FROM session WHERE hkey=?", (hkey,))
OperationalError: no such column: skey
----------------------------------------
```


Seems to me that there is a table not created/missing.

**Comment by jdoe0** [comment]
@Akendo: I'm trying to reproduce your error but, from the error message, I noticed that your source files seem to be different from the ones in my repo. For example, line 603 of [sync_app.py in my repo](https://github.com/jdoe0/ankisyncd/blob/dsnopek/AnkiServer/apps/sync_app.py) is `cursor = conn.cursor()` not `cursor.execute("SELECT skey, user, path FROM session WHERE hkey=?", (hkey,))`.

**Comment by timrae** [comment]
Nice work on this, I've gone ahead and added support to AnkiDroid, it's available in 2.6alpha2.

**Comment by Akendo** [comment]
I copied and pasted very badly this file from you commit into mine. I started the debug server and got the same result again:
```
akendo@x240 ~/s/anki-sync-server> python2 ./ankiserverctl.py debug example.ini 
Starting server in PID 14468.
serving on http://127.0.0.1:27701
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 54716)
Traceback (most recent call last):
  File "/home/akendo/.virtualenvs/anki-sync-server/lib/python2.7/site-packages/paste/httpserver.py", line 1085, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/home/akendo/.virtualenvs/anki-sync-server/lib/python2.7/site-packages/paste/httpserver.py", line 459, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/akendo/.virtualenvs/anki-sync-server/lib/python2.7/site-packages/paste/httpserver.py", line 454, in handle_one_request
    self.wsgi_execute()
  File "/home/akendo/.virtualenvs/anki-sync-server/lib/python2.7/site-packages/paste/httpserver.py", line 304, in wsgi_execute
    self.wsgi_start_response)
  File "/home/akendo/.virtualenvs/anki-sync-server/lib/python2.7/site-packages/paste/translogger.py", line 69, in __call__
    return self.application(environ, replacement_start_response)
  File "/home/akendo/.virtualenvs/anki-sync-server/lib/python2.7/site-packages/paste/urlmap.py", line 216, in __call__
    return app(environ, start_response)
  File "/home/akendo/.virtualenvs/anki-sync-server/lib/python2.7/site-packages/webob/dec.py", line 130, in __call__
    resp = self.call_func(req, *args, **self.kwargs)
  File "/home/akendo/.virtualenvs/anki-sync-server/lib/python2.7/site-packages/webob/dec.py", line 195, in call_func
    return self.func(req, *args, **kwargs)
  File "/home/akendo/src/anki-sync-server/AnkiServer/apps/sync_app.py", line 417, in __call__
    session = self.session_manager.load(hkey, self.create_session)
  File "/home/akendo/src/anki-sync-server/AnkiServer/apps/sync_app.py", line 606, in load
    cursor.execute("SELECT skey, user, path FROM session WHERE hkey=?", (hkey,))
OperationalError: no such column: skey
----------------------------------------
```

**Comment by Akendo** [comment]
This is when the client is connection to sync.

**Comment by Akendo** [comment]
I did reset my folder and the issue might be in the file `session.db ` after removing the file it seems to work.
So the error is mine. Great job!

**Comment by SenorFusion** [comment]
@dsnopek - It seems at least @jdoe0 and @Akendo have had success with this patch, and @timrae seems to think it will work as well since he merged the corresponding patch in AnkiDroid.

Would you be willing to test and merge this now? We could finally close #16.

And we could update the Readme to let users know they can finally use Anki Sync Server with Anki Droid! (I'm very excited about this!)

**Comment by dsnopek** [comment]
To expedite things, I just looked over the code and merged. :-) I'll do testing before making the next release and update the documentation then too.

Thanks everyone for your work on this! It's been 5-ish years since this code first began, it's great to finally have support in AnkiDroid! :-)

**Pull request merged**
